### PR TITLE
Update rakshasa.bat

### PR DESCRIPTION
**Pull request by double-beep**
The lines 10-14 and 19-32 appears very fast so a "pause" is very useful.
`pause` very useful!!

- [ ] Merge pull request #1 
@TheGeekman please answer

### CODE REVIEW

**Comment by double-beep** [comment]
HEY, where are you?

**Comment by TheGeekman** [comment]
Hi.

**Comment by TheGeekman** [comment]
Sure, why not (regarding the updates)?

**Comment by TheGeekman** [comment]
If you liked this, @double-beep, please check out https://github.com/TheGeekman/prank.vbs.

**Comment by double-beep** [comment]
I want only batchfile language. I do not like virtual basic.

**Comment by double-beep** [comment]
Will you merge this?It is useful change I think.

**Comment by double-beep** [comment]
Also, you did not merge pull request #1 but you put a tick.

**Comment by double-beep** [comment]
Hey, again the same?
Please press Merge Pull Request.

**Comment by TheGeekman** [comment]
@double-beep just created a new Batchfile repo. https://github.com/TheGeekman/mailman.bat

**Comment by double-beep** [comment]
Thanks!
Ok, I saw the mailman.bat
My suggestion is to open an organization and import there all your repositories.

**Comment by double-beep** [comment]
Thanks! 
Collaborator now!

**Comment by TheGeekman** [comment]
Possibly... Do you have any organizations?

**Comment by double-beep** [comment]
Yeah, go [here](https://github.com/Help-batch)

**Pull request merged**
